language:
- python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install coveralls
script:
- python dewey_tests.py
- coverage run dewey_tests.py
before_deploy:
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: &1
    secure: ldZiYvy66PWlM5l30uXKjzarUYmoGlQhL7FlEW+bmIFj72QPgoMFiGh19IzjacH55hoQeWXtyWgIsJqVENAfF0Vn41NLKfnxFIiMORzCX36k5kntAbN5OzJkL/xq4cjcOqzNqhBYcoufmaIrLfUnBniACiWb183joa9GUEwbH3CsSRUgJA+nhsstekHIJG3iLG3JpS+i4koU48f2fnWCXBxREGQvHGs9zc6UI6/fB01jK5eE/vCa/64ruwOTFiQok5tu68emYP5PyM1UmFsC/v+OxxVchpctff4JB7sTHkaJTeGo6XSh1D1Wn+LQrf/odhL+3Xhs011UZue8pxesiU8gj/fg5fQ3mGIUU7bBpjrA4ch18zQuwyzloV25vWDKq7Mu9UdAw2/P1owIlTYkg5TG94tiHEA8F3OoWXflhP3saLzR2WTP4jR2Z3F1kTPhZth0jw0voZXodO+RDhz2GiDBW0fUV5LLUuK/Lj8j3Tn3WDWxXq13jse9VOiFsgi1B7yKtBlUeSCcWWyskzEgIG2Gupn1lE0MfGNR9DhAWzpz0hQU9c038Nv8DadLuOrQKl+Ya18dSJS6ukz8e5OAL62STKNfavgGx3cldZJ+PdvZt1DFYkBL5bZCLqHa9r/52jDRF6pNQECIp2kZkMoDyZ2CRGJoHUAWSmD8egInS5I=
  secret_access_key: &2
    secure: 7xGccUtKEA52rouiAUoKW3+lrAlfDcLFFrUKeUvFOiEQB1+AEhnwrD1XLyWD3ckHkJnQFfCFyZUB36G7x0MfoXX1003S2y3FZPcQxIajexJqna/AhMi7obC+l35xnljo7bBtuasxuNlEr1RLhlqM9+2LUCe4QT8jgR3UBEu/c3nyfW3RStfTM+8wrKfYCNApSUyw8WEL7I3QqIuxM9jhQS00YOJV4PoQFX+rxO1L8AxaiDFvpXiaHQe5PxUo8mGvA4DCl1LphDP4skDzm2JCnL701qT2FbtVvZzAxiV04p+rapSfnSWP7w3gfEStYC/+D8q1VdzDi74CuR+Dln/jhMJBny5TJ4hGZkmXRNSTuBL7bYP59CMLnnovH4nI/MVEIKH7yMCB7JErXYwszHC+gBncXTR2eMr+gKlWP6CdcUh5RpJybAJxVTR6DrFk739QSVT5DWnL1L5EQIy6X5klAq38o1SL435r4a0oRko3sATv3J5CR9fbXyww/Y5MhOngfsB+0VUAB5mR8Z0rviBsvkWPtyO/zkfvV/Ag25szqfGjehJhADVHjhxWE3ArxHZYtdp6O/RJSqIWK5PrQKnnF6Txdh4DDdugcf2AzmmXNW+Fe0NAwaG2M8oT8FNbKTAeb+GXEQzjmK2aDep6tdt5h0B8/wpdnNouc4GMK5QKgBk=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &3
    repo: camelspeed/dewey
  bucket: camelspeed-dewey
  region: us-west-2
- provider: codedeploy
  access_key_id: *1
  secret_access_key: *2
  bucket: camelspeed-dewey
  key: latest.zip
  bundle_type: zip
  application: camelspeed-dewey-webapp
  deployment_group: camelspeed-dewey-webapps
  region: us-east-1
  on: *3
after_success:
- coveralls
